-- Seed: jury_feedback — demo ratings and testimonials for landing page
-- Auto-generated by scripts/generate_demo_premium_seed.js — do not edit manually
INSERT INTO jury_feedback (period_id, juror_id, rating, comment, is_public) VALUES
('a0d6f60d-ece4-40f8-aca2-955b4abc5d88', 'aaa0da50-6432-47e0-ab48-b01ca823ef19', 4, NULL, false),
('6c44b363-4522-4cad-a251-06484b72b164', 'f106ca15-dc12-414f-ac41-0b361db08f95', 5, 'Incredibly smooth experience. Scored 12 projects in under an hour with no hiccups.', true),
('6c44b363-4522-4cad-a251-06484b72b164', '2d3b2caa-0358-45c2-a122-c1c17cb9fbc5', 4, 'Clean interface, very intuitive. Would love a dark mode option on the scoring screen.', true),
('6c44b363-4522-4cad-a251-06484b72b164', '79ef4764-8e84-4a18-ad48-dbd780a5a027', 5, 'Best evaluation tool I have used for conference paper reviews. Simple yet powerful.', true),
('318124ea-8614-4355-ad48-2486524dfc13', 'f106ca15-dc12-414f-ac41-0b361db08f95', 5, NULL, false),
('318124ea-8614-4355-ad48-2486524dfc13', '2d3b2caa-0358-45c2-a122-c1c17cb9fbc5', 4, NULL, false),
('318124ea-8614-4355-ad48-2486524dfc13', '79ef4764-8e84-4a18-ad48-dbd780a5a027', 5, 'Used VERA again for the second time — consistently excellent.', true),
('47979751-163d-48b3-ae56-a65586d18f1b', '74499a66-86e7-4d92-ade1-70ba9b770ef0', 5, 'We evaluated 24 CanSat teams in a single afternoon. Real-time rankings kept the event exciting.', true),
('47979751-163d-48b3-ae56-a65586d18f1b', '4f32d322-afb7-4042-a9d1-ce0c17a09a30', 4, 'Great for competition settings. The rubric sheet was very helpful.', true),
('47979751-163d-48b3-ae56-a65586d18f1b', 'a71bad63-0a65-47a2-a5a5-623ab35c9ba7', 5, NULL, false),
('10abd4e8-0cb9-4853-a17c-ac40da311bff', '74499a66-86e7-4d92-ade1-70ba9b770ef0', 4, NULL, false),
('10abd4e8-0cb9-4853-a17c-ac40da311bff', '4f32d322-afb7-4042-a9d1-ce0c17a09a30', 5, 'Even better than last year. The admin panel gives instant insight into scoring patterns.', true),
('10abd4e8-0cb9-4853-a17c-ac40da311bff', 'a71bad63-0a65-47a2-a5a5-623ab35c9ba7', 4, 'Straightforward and efficient. No training needed — I just started scoring.', true),
('e14683dc-6ac1-4c73-a2cb-da24e9e4f45f', '47dcf645-bcf8-407e-a86e-f0e506495726', 5, 'Replaced our old paper-based system entirely. The export feature alone saves hours of work.', true),
('e14683dc-6ac1-4c73-a2cb-da24e9e4f45f', '44e14170-d567-4ad4-a771-cd269d538a2f', 4, 'Solid tool. The configurable criteria made it easy to adapt to our CS capstone format.', true),
('b90e1112-88c7-44fa-a275-25bc0ad2d96d', '47dcf645-bcf8-407e-a86e-f0e506495726', 5, NULL, false),
('b90e1112-88c7-44fa-a275-25bc0ad2d96d', '44e14170-d567-4ad4-a771-cd269d538a2f', 3, NULL, false),
('0e963024-a53f-4722-a9e0-5db7a47b4419', '47dcf645-bcf8-407e-a86e-f0e506495726', 4, NULL, false),
('0e963024-a53f-4722-a9e0-5db7a47b4419', '44e14170-d567-4ad4-a771-cd269d538a2f', 5, 'Third semester using VERA. It keeps getting better.', true),
('e77bf882-fc32-461c-acab-6ee1696df0c7', 'cec22180-51e9-4924-a2d0-6bca4aeb0028', 5, 'Yüzlerce takımı hızlıca değerlendirdik. Sistem çok stabil ve hızlıydı.', true),
('308d2708-dbea-41b6-a1c8-da6129445759', 'cec22180-51e9-4924-a2d0-6bca4aeb0028', 4, NULL, false),
('308d2708-dbea-41b6-a1c8-da6129445759', '27eea0b5-10e7-42eb-a739-4082ace54aa0', 5, 'Kullanımı çok kolay, eğitim bile gerekmedi. Tüm jüri arkadaşlarım memnun kaldı.', true),
('9f49cd18-d850-4b1e-ae53-c08253910f4e', '4f32d322-afb7-4042-a9d1-ce0c17a09a30', 3, NULL, false),
('9f49cd18-d850-4b1e-ae53-c08253910f4e', 'a71bad63-0a65-47a2-a5a5-623ab35c9ba7', 5, NULL, false)
ON CONFLICT (period_id, juror_id) DO NOTHING;
